using System;
using System.Collections.Generic;
using UnityEngine;

namespace ARArmDetection
{
    /// <summary>
    /// Rigid 3D layout of the ArUco markers attached to the mannequin arm, expressed
    /// in the ARM-LOCAL frame:
    ///
    ///   origin  = centre of the marker band, on the arm's long axis
    ///   +Z      = along the arm toward the WRIST (distal)
    ///   +X      = facet 0's outward normal
    ///
    /// The band is a faceted prism (markers must stay FLAT — a marker curved around
    /// the arm decodes poorly and reports a wrong pose): print the band with
    /// Training/scripts/make_marker_band.py, fold at the facet lines, and wrap it
    /// around the upper-arm end. The printed band's TOP edge goes toward the
    /// SHOULDER (marker "up" = -Z here; keep both in sync).
    ///
    /// Extra markers (e.g. one on the flat shoulder cross-section disc) can be added
    /// in the inspector with an explicit local position/rotation.
    /// </summary>
    [Serializable]
    public class MarkerBandLayout
    {
        [Header("Faceted band (generated by make_marker_band.py)")]
        [Tooltip("Number of flat facets the printed band is folded into.")]
        [Range(3, 12)] public int Facets = 6;

        [Tooltip("Distance (m) from the arm axis to each FLAT facet face (the polygon apothem). " +
                 "make_marker_band.py prints the matching value for your arm circumference.")]
        public float FacetApothemMeters = 0.0445f;

        [Tooltip("Printed marker side length (m), black border included.")]
        public float MarkerSizeMeters = 0.04f;

        [Tooltip("ArUco id of facet 0; facet i uses FirstMarkerId + i (DICT_4X4_50).")]
        public int FirstMarkerId = 0;

        [Tooltip("Flip if the printed band is wrapped the other way around the arm " +
                 "(overlay orbits the wrong direction when the arm rotates).")]
        public bool ReverseWrapDirection;

        [Header("Extra markers (optional, e.g. shoulder disc)")]
        public List<ExtraMarker> ExtraMarkers = new();

        [Serializable]
        public class ExtraMarker
        {
            public int Id = 10;
            public float SizeMeters = 0.05f;
            [Tooltip("Marker centre in arm-local space (m).")]
            public Vector3 LocalPosition = new(0f, 0f, -0.06f);
            [Tooltip("Marker orientation in arm-local space: the marker's face normal is " +
                     "its local -Z ... the rotation maps marker-local axes (X right, Y up, " +
                     "Z out of the printed face toward the viewer) into arm space.")]
            public Vector3 LocalEulerAngles = new(0f, 180f, 0f);
        }

        /// <summary>
        /// Returns the 4 arm-local corner positions of the marker with this id in
        /// ArUco order (TL, TR, BR, BL as seen looking at the printed face).
        /// False when the id is not part of the layout.
        /// </summary>
        public bool TryGetMarkerCorners(int id, Vector3[] corners)
        {
            if (corners == null || corners.Length < 4) return false;

            int facet = id - FirstMarkerId;
            if (facet >= 0 && facet < Facets)
            {
                float theta = facet * Mathf.PI * 2f / Facets * (ReverseWrapDirection ? -1f : 1f);
                Vector3 normal = new(Mathf.Cos(theta), Mathf.Sin(theta), 0f);
                // "Right" as seen from outside the band, "up" toward the shoulder (-Z).
                Vector3 right = Vector3.Cross(Vector3.forward, normal).normalized
                              * (ReverseWrapDirection ? -1f : 1f);
                Vector3 up = -Vector3.forward;
                FillCorners(normal * FacetApothemMeters, right, up, MarkerSizeMeters, corners);
                return true;
            }

            for (int i = 0; i < ExtraMarkers.Count; i++)
            {
                var m = ExtraMarkers[i];
                if (m.Id != id) continue;
                Quaternion rot = Quaternion.Euler(m.LocalEulerAngles);
                FillCorners(m.LocalPosition, rot * Vector3.right, rot * Vector3.up, m.SizeMeters, corners);
                return true;
            }

            return false;
        }

        private static void FillCorners(Vector3 center, Vector3 right, Vector3 up, float size, Vector3[] corners)
        {
            Vector3 r = right * (size * 0.5f);
            Vector3 u = up * (size * 0.5f);
            corners[0] = center - r + u; // TL
            corners[1] = center + r + u; // TR
            corners[2] = center + r - u; // BR
            corners[3] = center - r - u; // BL
        }
    }
}
